### ISSUE TITLE
update and publish

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ig-template#4]
update the template according to hl7 and publish a stable version (ci build lasts only 3 month)

**Comment by oliveregger** [comment]
plus history Template Prozess anpassen und angleichen mit hl7 approach

**Comment by ziegm** [comment]
https://fhir.ch/ig/ch-core/StructureDefinition-ch-core-composition.profile.json.html
The tabs 'XML', 'JSON' and 'TTL' for the profiles are missing. The pages were generated, see example above.

**Comment by oliveregger** [comment]
- composition profile wieder ok
- history template von hl7 übernommen und nicht mehr das eigene
